name: "Minimum reviewers"
description: "Checking minimum reviewers before merge pull request"
author: "ning.nattarat@gmail.com"

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'